name: tests

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        target: [
          #aarch64-linux-gnu,
          #aarch64-linux-musl,
          #riscv64-linux-gnu,
          #rsicv64-linux-musl,
          x86_64-linux-gnu,
          x86_64-linux-musl,
        ]
    runs-on: ${{ matrix.os }}
    name: Build and Test ${{ matrix.os }}, ${{ matrix.target }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # github VMs only support x64 for now so we need QEMU
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
          cache-image: true

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0-dev.3357+c44f4501e

      - name: Run Tests
        run: zig build test -Dtarget=${{ matrix.target }} -fqemu