name: tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        target: [
          aarch64-linux-gnu,
          aarch64-linux-musl,
          x86_64-linux-gnu,
          x86_64-linux-musl,
          # maybe in the future!
          # x86-linux-gnu
        ]
    runs-on: ${{ matrix.os }}
    name: Build and Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: Run Tests
        run: zig build test -Dtarget=${{ matrix.target }}